name: elearningapp
description: "A cross-platform E-learning management application."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.0

  sqflite_common_ffi: ^2.3.2

  # --- 1. Firebase Ecosystem - Downgrade về phiên bản ổn định ---
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4


  # --- 2. Offline & Local Storage ---
  sqflite: ^2.3.3
  path: ^1.9.0
  shared_preferences: ^2.3.2
  internet_connection_checker_plus: ^2.5.2

  # --- 3. Utilities ---
  intl: ^0.19.0
  uuid: ^4.5.1
  csv: ^6.0.0
  file_picker: ^8.1.2

  # --- 4. State Management & DI ---
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  equatable: ^2.0.5

  # --- 5. UI Components ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # --- Code Generation ---
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true